---
sip:
  caller: "sip:klingel1@fritz.box"
  callee: "sip:**611@fritz.box"
  maxRingingTime: 5s
  server:
    host: "fritz.box"
    port: 5060
    user: klingel1
    password: "password001"
    debug: false

statusLed:
  gpio: 18
  blinkDuration: 10s

externalBell:
  gpio: 25
  ringDuration: 2s

bellPushes:
  - label: Main door
    gpio: 23
  - label: Garden Door
    gpio: 24

logging:
  target: stdout

  debug: false

controller:
  socket: ./raspidoor.socket

disableGpio: true
