---
# Defines the TCP address to listen for HTTP connections
address: ":8080"

# Defines the path of the Unix socket to listen on for controller commands.
socket: ../daemon/raspidoor.socket

logging:
  # target defines where to write logs: stdout or syslog
  target: stdout
