name: CI

on:
  push:

jobs:
  test:
    name: Build & Test    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.18.0"

      - name: Build daemon
        run: go build 
        working-directory: daemon

      - name: Run daemon tests
        run: go test ./... -cover
        working-directory: daemon

      - name: Build cli
        run: go build 
        working-directory: cli

      - name: Run cli tests
        run: go test ./... -cover
        working-directory: cli

      - name: Build webapp
        run: go build 
        working-directory: webapp

      - name: Run webapp tests
        run: go test ./... -cover
        working-directory: webapp
